# Model Evaluation
This notebook evaluates the trained model on the test set and generates performance metrics.

In [1]:
import torch
from sklearn.metrics import classification_report, confusion_matrix
%run 01_preprocessing.ipynb
%run 02_model_training.ipynb

## Generate Summary Metric on Test Set

In [2]:
# function to display summary metrics
def summary_metrics(model, X_test_t, y_test_t):
    model.eval()
    with torch.no_grad():
        preds = model(X_test_t).argmax(dim=1)

    print("Classification Report:")
    print(classification_report(y_test_t, preds))

    print("Confusion Matrix:")
    cm = confusion_matrix(y_test_t, preds)
    print(cm)

    # overall accuracy
    accuracy = (preds == y_test_t).float().mean().item()
    print(f"\nOverall Test Accuracy: {accuracy:.4f}")
    print(f"Correct Predictions: {(preds == y_test_t).sum().item()}/{len(y_test_t)}")

In [3]:
# main function to run the model training and evaluation
def main(data_src="final_dataset.csv"):
    model, X_test_t, y_test_t = risk_classifier(data_src)
    summary_metrics(model, X_test_t, y_test_t)

main()

Classification Report:
              precision    recall  f1-score   support

           0       0.55      0.88      0.68      4973
           1       0.55      0.45      0.49      3213
           2       0.76      0.58      0.66      9643

    accuracy                           0.64     17829
   macro avg       0.62      0.63      0.61     17829
weighted avg       0.67      0.64      0.63     17829

Confusion Matrix:
[[4353  179  441]
 [ 484 1432 1297]
 [3086  977 5580]]

Overall Test Accuracy: 0.6374
Correct Predictions: 11365/17829
